<a href="https://www.kaggle.com/code/ebubekirtilbac/flo-rfm-analysis?scriptVersionId=226811264" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/flo-crm-data/flo_data_20k.csv

**FLO CRM DATASET**

![FLO CRM DATASET](https://www.mngavm.com/wp-content/uploads/2022/12/166b4b9a6db1bc18d0535864982ab055.png)

In [2]:
#DATA UNDERSTANDING AND PREPARING
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 500)
df_=pd.read_csv(r"/kaggle/input/flo-crm-data/flo_data_20k.csv")
df=df_.copy()

In [3]:
###DATA CHECKING####

def df_check(df, head_rows=5):
    print(df.shape)
    print(df.dtypes)
    print(df.head(head_rows))
    print(df.tail(head_rows))
    print(df.describe().T)
    print(df.isnull().sum())
    print(df.memory_usage(deep=True))

df_check(df)

(19945, 12)
master_id                             object
order_channel                         object
last_order_channel                    object
first_order_date                      object
last_order_date                       object
last_order_date_online                object
last_order_date_offline               object
order_num_total_ever_online          float64
order_num_total_ever_offline         float64
customer_value_total_ever_offline    float64
customer_value_total_ever_online     float64
interested_in_categories_12           object
dtype: object
                              master_id order_channel last_order_channel first_order_date last_order_date last_order_date_online last_order_date_offline  order_num_total_ever_online  order_num_total_ever_offline  customer_value_total_ever_offline  customer_value_total_ever_online       interested_in_categories_12
0  cc294636-19f0-11eb-8d74-000d3a38a36f   Android App            Offline       2020-10-30      2021-02-26             2021-02-21              2021-02-26                          4.0                           1.0                             139.99                            799.38                           [KADIN]
1  f431bd5a-ab7b-11e9-a2fc-000d3a38a36f   Android App             Mobile       2017-02-08      2021-02-16             2021-02-16              2020-01-10                         19.0                           2.0                             159.97                           1853.58  [ERKEK, COCUK, KADIN, AKTIFSPOR]
2  69b69676-1a40-11ea-941b-000d3a38a36f   Android App        Android App       2019-11-27      2020-11-27             2020-11-27              2019-12-01                          3.0                           2.0                             189.97                            395.35                    [ERKEK, KADIN]
3  1854e56c-491f-11eb-806e-000d3a38a36f   Android App        Android App       2021-01-06      2021-01-17             2021-01-17              2021-01-06                          1.0                           1.0                              39.99                             81.98               [AKTIFCOCUK, COCUK]
4  d6ea1074-f1f5-11e9-9346-000d3a38a36f       Desktop            Desktop       2019-08-03      2021-03-07             2021-03-07              2019-08-03                          1.0                           1.0                              49.99                            159.99                       [AKTIFSPOR]
                                  master_id order_channel last_order_channel first_order_date last_order_date last_order_date_online last_order_date_offline  order_num_total_ever_online  order_num_total_ever_offline  customer_value_total_ever_offline  customer_value_total_ever_online interested_in_categories_12
19940  727e2b6e-ddd4-11e9-a848-000d3a38a36f   Android App            Offline       2019-09-21      2020-07-05             2020-06-05              2020-07-05                          1.0                           2.0                             289.98                            111.98          [ERKEK, AKTIFSPOR]
19941  25cd53d4-61bf-11ea-8dd8-000d3a38a36f       Desktop            Desktop       2020-03-01      2020-12-22             2020-12-22              2020-03-01                          1.0                           1.0                             150.48                            239.99                 [AKTIFSPOR]
19942  8aea4c2a-d6fc-11e9-93bc-000d3a38a36f       Ios App            Ios App       2019-09-11      2021-05-24             2021-05-24              2019-09-11                          2.0                           1.0                             139.98                            492.96                 [AKTIFSPOR]
19943  e50bb46c-ff30-11e9-a5e8-000d3a38a36f   Android App        Android App       2019-03-27      2021-02-13             2021-02-13              2021-01-08                          1.0                           5.0                             711.79                            297.98          [ERKEK, AKTIFSPOR]
19944  740998d2-b1f7-11e9-89fa-000d3a38a36f   Android App        Android App       2019-09-03      2020-06-06             2020-06-06              2019-09-03                          1.0                           1.0                              39.99                            221.98          [KADIN, AKTIFSPOR]
                                     count        mean         std    min     25%     50%     75%       max
order_num_total_ever_online        19945.0    3.110855    4.225647   1.00    1.00    2.00    4.00    200.00
order_num_total_ever_offline       19945.0    1.913913    2.062880   1.00    1.00    1.00    2.00    109.00
customer_value_total_ever_offline  19945.0  253.922597  301.532853  10.00   99.99  179.98  319.97  18119.14
customer_value_total_ever_online   19945.0  497.321690  832.601886  12.99  149.98  286.46  578.44  45220.13
master_id                            0
order_channel                        0
last_order_channel                   0
first_order_date                     0
last_order_date                      0
last_order_date_online               0
last_order_date_offline              0
order_num_total_ever_online          0
order_num_total_ever_offline         0
customer_value_total_ever_offline    0
customer_value_total_ever_online     0
interested_in_categories_12          0
dtype: int64
Index                                    128
master_id                            1854885
order_channel                        1309578
last_order_channel                   1300440
first_order_date                     1336315
last_order_date                      1336315
last_order_date_online               1336315
last_order_date_offline              1336315
order_num_total_ever_online           159560
order_num_total_ever_offline          159560
customer_value_total_ever_offline     159560
customer_value_total_ever_online      159560
interested_in_categories_12          1412437
dtype: int64

*****Let’s create new variables for each customer’s total number of purchases and total spending.** ****![](https://www.zeneks.com.tr/wp-content/uploads/2022/11/KURUMSAL-CRM2.png)

In [4]:
df["total_order_num"] = df["order_num_total_ever_offline"] + df["order_num_total_ever_online"]
df["total_customer_value"] = df["customer_value_total_ever_offline"] + df["customer_value_total_ever_online"]

In [5]:
for col in df.columns:
    if "date" in col:
        print(col)
        df[col] = pd.to_datetime(df[col])

df.info()

first_order_date
last_order_date
last_order_date_online
last_order_date_offline
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19945 entries, 0 to 19944
Data columns (total 14 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   master_id                          19945 non-null  object
 1   order_channel                      19945 non-null  object
 2   last_order_channel                 19945 non-null  object
 3   first_order_date                   19945 non-null  datetime64[ns]
 4   last_order_date                    19945 non-null  datetime64[ns]
 5   last_order_date_online             19945 non-null  datetime64[ns]
 6   last_order_date_offline            19945 non-null  datetime64[ns]
 7   order_num_total_ever_online        19945 non-null  float64
 8   order_num_total_ever_offline       19945 non-null  float64
 9   customer_value_total_ever_offline  19945 non-null  float64
 10  customer_value_total_ever_online   19945 non-null  float64
 11  interested_in_categories_12        19945 non-null  object
 12  total_order_num                    19945 non-null  float64
 13  total_customer_value               19945 non-null  float64
dtypes: datetime64[ns](4), float64(6), object(4)
memory usage: 2.1+ MB

*****Let’s examine the distribution of the number of customers, the average number of products purchased, and the average spending across shopping channels.*****

In [6]:
df.groupby("order_channel").agg({"total_customer_value":"mean", "total_order_num": "mean"})

               total_customer_value  total_order_num
order_channel
Android App              823.492655         5.504897
Desktop                  588.782984         3.992687
Ios App                  891.634285         5.418637
Mobile                   620.275125         4.440598

***Let’s rank the top 10 customers generating the highest revenue.***

In [7]:
df[["master_id", "total_customer_value"]].sort_values("total_customer_value", ascending=False).head(10)

                                  master_id  total_customer_value
11150  5d1c466a-9cfd-11e9-9897-000d3a38a36f              45905.10
4315   d5ef8058-a5c6-11e9-a2fc-000d3a38a36f              36818.29
7613   73fd19aa-9e37-11e9-9897-000d3a38a36f              33918.10
13880  7137a5c0-7aad-11ea-8f20-000d3a38a36f              31227.41
9055   47a642fe-975b-11eb-8c2a-000d3a38a36f              20706.34
7330   a4d534a2-5b1b-11eb-8dbd-000d3a38a36f              18443.57
8068   d696c654-2633-11ea-8e1c-000d3a38a36f              16918.57
163    fef57ffa-aae6-11e9-a2fc-000d3a38a36f              12726.10
7223   cba59206-9dd1-11e9-9897-000d3a38a36f              12282.24
18767  fc0ce7a4-9d87-11e9-9897-000d3a38a36f              12103.15

***Let’s rank the top 10 customers with the highest number of orders.***

In [8]:
df[["master_id", "total_order_num"]].sort_values("total_order_num", ascending=False).head(10)

                                  master_id  total_order_num
11150  5d1c466a-9cfd-11e9-9897-000d3a38a36f            202.0
7223   cba59206-9dd1-11e9-9897-000d3a38a36f            131.0
8783   a57f4302-b1a8-11e9-89fa-000d3a38a36f            111.0
2619   fdbe8304-a7ab-11e9-a2fc-000d3a38a36f             88.0
6322   329968c6-a0e2-11e9-a2fc-000d3a38a36f             83.0
7613   73fd19aa-9e37-11e9-9897-000d3a38a36f             82.0
9347   44d032ee-a0d4-11e9-a2fc-000d3a38a36f             77.0
10954  b27e241a-a901-11e9-a2fc-000d3a38a36f             75.0
8068   d696c654-2633-11ea-8e1c-000d3a38a36f             70.0
7330   a4d534a2-5b1b-11eb-8dbd-000d3a38a36f             70.0

**LET’S CALCULATE THE RFM METRICS.**

***RFM:“RFM (Recency, Frequency, Monetary) is a customer segmentation technique that analyzes how recently, how often, and how much a customer spends.”***


![](http://analyticahouse.com/Website/assets/img/Blogs/6314b7a379496.png)

In [9]:
import datetime as dt
max_date = df["last_order_date"].max()
today_date = max_date + dt.timedelta(days=2)

rfm = df.groupby("master_id").agg({"last_order_date": lambda date: (today_date - date.max()).days,
                             "total_order_num": lambda order: order.sum(),
                             "total_customer_value": lambda value: value.sum()})
rfm.columns = ["recency", "frequency", "monetary"]
rfm.head(10)

                                      recency  frequency  monetary
master_id
00016786-2f5a-11ea-bb80-000d3a38a36f       10        5.0    776.07
00034aaa-a838-11e9-a2fc-000d3a38a36f      298        3.0    269.47
000be838-85df-11ea-a90b-000d3a38a36f      213        4.0    722.69
000c1fe2-a8b7-11ea-8479-000d3a38a36f       27        7.0    874.16
000f5e3e-9dde-11ea-80cd-000d3a38a36f       20        7.0   1620.33
00136ce2-a562-11e9-a2fc-000d3a38a36f      203        2.0    359.45
00142f9a-7af6-11eb-8460-000d3a38a36f       25        3.0    404.94
0014778a-5b11-11ea-9a2c-000d3a38a36f       26        3.0    727.43
0018c6aa-ab6c-11e9-a2fc-000d3a38a36f      126        2.0    317.91
0022f41e-5597-11eb-9e65-000d3a38a36f       12        2.0    154.98

In [10]:
##Calculation of RF and RFM Scores

##RF Score (Recency & Frequency): A combined metric that evaluates how recently and how often a customer makes purchases.
##	RFM Score (Recency, Frequency, Monetary): A customer segmentation model that considers how recently a customer purchased, how often they buy, and how much they spend.


rfm["recency_score"] = pd.qcut(rfm['recency'], 5, labels=[5, 4, 3, 2, 1])
rfm["frequency_score"] = pd.qcut(rfm["frequency"].rank(method="first"), 5, labels=[1, 2, 3, 4, 5])
rfm["monetary_score"] = pd.qcut(rfm['monetary'], 5, labels=[1, 2, 3, 4, 5])
rfm["RF_SCORE"] = (rfm['recency_score'].astype(str) +
                    rfm['frequency_score'].astype(str))

rfm.head()

                                      recency  frequency  monetary recency_score frequency_score monetary_score RF_SCORE
master_id
00016786-2f5a-11ea-bb80-000d3a38a36f       10        5.0    776.07             5               4              4       54
00034aaa-a838-11e9-a2fc-000d3a38a36f      298        3.0    269.47             1               2              1       12
000be838-85df-11ea-a90b-000d3a38a36f      213        4.0    722.69             2               3              4       23
000c1fe2-a8b7-11ea-8479-000d3a38a36f       27        7.0    874.16             5               4              4       54
000f5e3e-9dde-11ea-80cd-000d3a38a36f       20        7.0   1620.33             5               4              5       54

***Let’s define RF scores as segments***

In [11]:
segment_map = {
    r'[1-2][1-2]': 'hibernating',
    r'[1-2][3-4]': 'at_risk',
    r'[1-2]5': 'cant_loose',
    r'3[1-2]': 'about_to_sleep',
    r'33': 'need_attention',
    r'[3-4][4-5]': 'loyal_customers',
    r'41': 'promising',
    r'51': 'new_customers',
    r'[4-5][2-3]': 'potential_loyalists',
    r'5[4-5]': 'champions'
}

rfm['segment'] = rfm['RF_SCORE'].replace(segment_map, regex=True)

rfm.head()

                                      recency  frequency  monetary recency_score frequency_score monetary_score RF_SCORE      segment
master_id
00016786-2f5a-11ea-bb80-000d3a38a36f       10        5.0    776.07             5               4              4       54    champions
00034aaa-a838-11e9-a2fc-000d3a38a36f      298        3.0    269.47             1               2              1       12  hibernating
000be838-85df-11ea-a90b-000d3a38a36f      213        4.0    722.69             2               3              4       23      at_risk
000c1fe2-a8b7-11ea-8479-000d3a38a36f       27        7.0    874.16             5               4              4       54    champions
000f5e3e-9dde-11ea-80cd-000d3a38a36f       20        7.0   1620.33             5               4              5       54    champions

***Let’s analyze the average recency, frequency, and monetary values of the segments.***

In [12]:
rfm[["segment", "recency", "frequency", "monetary"]].groupby("segment").agg(["mean", "count"])

                        recency        frequency           monetary
                           mean count       mean count         mean count
segment
about_to_sleep       114.031649  1643   2.406573  1643   361.649373  1643
at_risk              242.328997  3152   4.470178  3152   648.325038  3152
cant_loose           235.159129  1194  10.716918  1194  1481.652446  1194
champions             17.142187  1920   8.965104  1920  1410.708938  1920
hibernating          247.426303  3589   2.391474  3589   362.583299  3589
loyal_customers       82.557926  3375   8.356444  3375  1216.257224  3375
need_attention       113.037221   806   3.739454   806   553.436638   806
new_customers         17.976226   673   2.000000   673   344.049495   673
potential_loyalists   36.869744  2925   3.310769  2925   533.741344  2925
promising             58.694611   668   2.000000   668   334.153338   668

**Mission time**




**Case 1: FLO is adding a new women’s shoe brand to its portfolio. The prices of this brand’s products are above the general customer preferences. Therefore, they want to communicate specifically with customers who match the target profile for brand promotion and product sales. Loyal customers (champions, loyal_customers) who have spent over 250 TL on average and have purchased from the women’s category will be contacted. Save the master_id numbers of these customers in a CSV file named new_brand_target_customer_id.csv.**

In [13]:
combined = pd.merge(df, rfm, on="master_id")

combined[((combined["segment"] == "champions") | 
          (combined["segment"] == "loyal_customers")) & 
         ((combined["total_customer_value"] / combined["total_order_num"]) > 250) & 
         (combined["interested_in_categories_12"].str.contains("KADIN"))]["master_id"]

74       8423eda8-ae37-11e9-a2fc-000d3a38a36f
136      37753730-9b69-11ea-a27a-000d3a38a36f
1078     df760a84-ab25-11e9-a2fc-000d3a38a36f
1134     fdd08240-244a-11ea-a30f-000d3a38a36f
1323     1df22bd2-8549-11ea-80af-000d3a38a36f
1484     aa100b7a-d667-11e9-93bc-000d3a38a36f
1574     f2affcfc-f186-11e9-9346-000d3a38a36f
1682     667a10cc-4fa2-11ea-99ba-000d3a38a36f
2002     f1e095a6-637e-11ea-a6dc-000d3a38a36f
2060     3a2a6c48-526c-11ea-956d-000d3a38a36f
2246     169d1518-9d6e-11e9-9897-000d3a38a36f
2401     1e4fcad2-a57d-11e9-a2fc-000d3a38a36f
2542     70d34b80-a7e4-11e9-a2fc-000d3a38a36f
2763     215e3162-565a-11ea-b9b9-000d3a38a36f
3157     25a05fe6-5a84-11eb-9e65-000d3a38a36f
3274     c2984396-d622-11e9-93bc-000d3a38a36f
3662     63caf5e4-e3be-11e9-ad00-000d3a38a36f
3879     b43a543e-5b96-11ea-a3e9-000d3a38a36f
3932     f8033de8-b16e-11e9-89fa-000d3a38a36f
3996     715f95a2-9f94-11e9-a2fc-000d3a38a36f
4016     b95511d4-aa3e-11e9-a2fc-000d3a38a36f
4130     ea56ef18-b1a1-11e9-89fa-000d3a38a36f
4157     7eed6468-4540-11ea-acaf-000d3a38a36f
4164     f834dad8-316a-11eb-9dc6-000d3a38a36f
4176     fdbebc0a-d60b-11e9-93bc-000d3a38a36f
4315     d5ef8058-a5c6-11e9-a2fc-000d3a38a36f
4344     6b05a082-d60a-11e9-93bc-000d3a38a36f
4699     a80e3c10-aa7b-11e9-a2fc-000d3a38a36f
5199     aae88ace-afd7-11e9-9757-000d3a38a36f
5303     74fa83b0-5327-11ea-acd3-000d3a38a36f
5347     0c7849ac-8bf4-11ea-8ec0-000d3a38a36f
5407     307e72f4-7ca4-11ea-80af-000d3a38a36f
5457     78566b7e-174e-11ea-9213-000d3a38a36f
5465     f9561e98-6741-11ea-9d38-000d3a38a36f
5553     f66114fa-a0d5-11e9-a2fc-000d3a38a36f
5645     b3b9f10c-b0c1-11e9-9757-000d3a38a36f
5775     e31293ac-d63a-11e9-93bc-000d3a38a36f
6045     27df9380-2a82-11eb-b280-000d3a38a36f
6334     3a1c5af4-5ec9-11ea-be5b-000d3a38a36f
6416     f2964aa8-ac69-11e9-a2fc-000d3a38a36f
6484     ec547c8c-bd11-11ea-aa61-000d3a38a36f
6666     53fe00d4-7b7a-11eb-960b-000d3a38a36f
6717     40b4f318-9dfb-11eb-9c47-000d3a38a36f
6791     00b3ee24-aa44-11e9-a2fc-000d3a38a36f
6835     bd458b26-b1e0-11e9-89fa-000d3a38a36f
7071     7b1a342c-a551-11e9-a2fc-000d3a38a36f
7171     77e66e92-31fa-11eb-860c-000d3a38a36f
7241     5a1117f4-204a-11ea-87bf-000d3a38a36f
7272     d186774a-b095-11e9-9757-000d3a38a36f
7312     90befc98-925a-11eb-b584-000d3a38a36f
7330     a4d534a2-5b1b-11eb-8dbd-000d3a38a36f
7604     c86c876e-1f1a-11ea-87bf-000d3a38a36f
7613     73fd19aa-9e37-11e9-9897-000d3a38a36f
7692     38b56878-a0f0-11e9-a2fc-000d3a38a36f
7715     f3cee874-bde0-11ea-aa61-000d3a38a36f
8003     dd270486-acf1-11e9-a2fc-000d3a38a36f
8218     be3cd392-302c-11eb-be61-000d3a38a36f
8220     ca229254-531f-11ea-acd3-000d3a38a36f
8575     e40c9932-a55d-11e9-a2fc-000d3a38a36f
8687     a1672a2a-b070-11e9-9757-000d3a38a36f
8810     1348781e-134b-11ea-a001-000d3a38a36f
8826     75bc0a4a-a840-11e9-a2fc-000d3a38a36f
9073     2162cf82-5b0b-11ea-b73b-000d3a38a36f
9226     7d2029ba-5457-11ea-b1db-000d3a38a36f
9250     4c2a7404-b0ac-11e9-9757-000d3a38a36f
9579     19a9c11e-5bf2-11ea-8fe9-000d3a38a36f
10628    c7686de8-41ba-11ea-96d9-000d3a38a36f
10638    a0bc13aa-d641-11e9-93bc-000d3a38a36f
10669    b08ec0a6-e1e1-11e9-957d-000d3a38a36f
10864    6b64c6fc-d6f0-11e9-93bc-000d3a38a36f
10963    77203218-1dce-11ea-8bf2-000d3a38a36f
11400    eee9cab4-ab75-11e9-a2fc-000d3a38a36f
11415    4dac5fa4-b0de-11e9-9757-000d3a38a36f
11447    02355648-60f1-11ea-8dd8-000d3a38a36f
11475    ecb3159a-5bb3-11ea-a117-000d3a38a36f
11570    da663f30-b149-11e9-9757-000d3a38a36f
11609    fac5ea30-a7eb-11e9-a2fc-000d3a38a36f
11648    07f783c4-d6d3-11e9-93bc-000d3a38a36f
12004    ae8c7a38-5bed-11ea-bbe9-000d3a38a36f
12095    c4624b84-48e2-11eb-806e-000d3a38a36f
12157    492f9cf0-6e04-11ea-84a8-000d3a38a36f
12336    83f320f0-a7ed-11ea-bd63-000d3a38a36f
12438    625f40a2-5bd2-11ea-98b0-000d3a38a36f
12451    156e5a8a-1b09-11ea-a050-000d3a38a36f
12525    edff6c14-2bed-11ea-91ab-000d3a38a36f
12778    95706470-1e38-11eb-8d74-000d3a38a36f
12885    28059d2a-97eb-11ea-9d91-000d3a38a36f
12987    26ea9bb0-a756-11e9-a2fc-000d3a38a36f
13036    a15599ae-b3b7-11ea-8745-000d3a38a36f
13207    b93f8a4a-d6ca-11e9-93bc-000d3a38a36f
13321    75cf3d32-3d27-11ea-9e19-000d3a38a36f
13478    0b168a06-af18-11e9-a2fc-000d3a38a36f
13556    9c0e0a46-fe52-11e9-a5e8-000d3a38a36f
13596    7bb19f04-97f6-11ea-9d91-000d3a38a36f
13683    3339434a-b173-11e9-89fa-000d3a38a36f
13763    14f8f5a0-ff21-11e9-a5e8-000d3a38a36f
13842    d9bdafb2-b001-11e9-9757-000d3a38a36f
13852    8c07073c-a561-11e9-a2fc-000d3a38a36f
13880    7137a5c0-7aad-11ea-8f20-000d3a38a36f
14042    4864632c-441f-11eb-806e-000d3a38a36f
14059    8569918e-ab23-11e9-a2fc-000d3a38a36f
14339    486f3954-11b8-11ea-af12-000d3a38a36f
14425    c444d876-137f-11eb-8ffc-000d3a38a36f
14477    08f0e73e-a587-11e9-a2fc-000d3a38a36f
14563    5c6681b6-490b-11eb-806e-000d3a38a36f
15438    c610aeb8-a79d-11e9-a2fc-000d3a38a36f
15552    7e10b500-5b0b-11ea-9b03-000d3a38a36f
16018    e101681a-6648-11ea-82da-000d3a38a36f
16133    483e2ab4-3033-11ea-bb28-000d3a38a36f
16169    24d4efb2-a9c5-11e9-a2fc-000d3a38a36f
16464    8826faf6-a4c5-11e9-a2fc-000d3a38a36f
16686    fbc88b3a-2929-11ea-b87a-000d3a38a36f
16886    18c523d4-1a79-11ea-941b-000d3a38a36f
16927    5ad03fde-b0f2-11e9-9757-000d3a38a36f
16979    625a6ab6-a7e9-11e9-a2fc-000d3a38a36f
17024    26c66b9e-8bc3-11ea-8ec0-000d3a38a36f
17196    bdb5224e-5bfb-11eb-8dbd-000d3a38a36f
17268    8aa34b16-abb6-11e9-a2fc-000d3a38a36f
17270    4e2b2704-a8d1-11e9-a2fc-000d3a38a36f
17430    1458cb58-aefd-11e9-a2fc-000d3a38a36f
17502    1c955302-b0d5-11e9-9757-000d3a38a36f
17653    07b6055a-114f-11ea-8872-000d3a38a36f
17919    8133d6f2-ee07-11e9-9346-000d3a38a36f
17963    8fd88976-6708-11ea-9d38-000d3a38a36f
18122    27a7e4d8-ac59-11e9-a2fc-000d3a38a36f
18166    6385c3ea-d679-11e9-93bc-000d3a38a36f
18183    bfb92790-a7e6-11e9-a2fc-000d3a38a36f
18193    c52fcb34-ffd9-11e9-a5e8-000d3a38a36f
18227    ae33cad6-52ed-11ea-9ade-000d3a38a36f
18460    fde9f7d2-b0ac-11e9-9757-000d3a38a36f
18501    e53cf078-acf5-11e9-a2fc-000d3a38a36f
18522    529964d6-97ff-11ea-9d91-000d3a38a36f
18874    e9c13f58-b2a6-11e9-8f1b-000d3a38a36f
19052    67d758f2-976a-11ea-a9c8-000d3a38a36f
19124    77f2a668-a94c-11e9-a2fc-000d3a38a36f
19221    f48e6a1c-ff1f-11e9-a5e8-000d3a38a36f
19224    45f82aaa-6b63-11ea-9c62-000d3a38a36f
19346    e42a05aa-29e0-11ea-87cc-000d3a38a36f
19388    b3b9fd72-851f-11ea-80af-000d3a38a36f
19396    67a4d436-2352-11ea-8523-000d3a38a36f
19455    fefb852a-2580-11ea-b1c8-000d3a38a36f
19505    bee55d6e-f27a-11e9-9346-000d3a38a36f
19609    ef3cb46c-a388-11e9-a2fc-000d3a38a36f
19716    8ff632e0-a166-11e9-a2fc-000d3a38a36f
19856    07bcae98-a81b-11e9-a2fc-000d3a38a36f
Name: master_id, dtype: object

In [14]:
combined[((combined["segment"] == "champions") | 
          (combined["segment"] == "loyal_customers")) & 
         ((combined["total_customer_value"] / combined["total_order_num"]) > 250) & 
         (combined["interested_in_categories_12"].str.contains("KADIN"))]["master_id"].to_csv("new_brand_target_customer_id.csv")
print(pd.read_csv("new_brand_target_customer_id.csv").head(20))

    Unnamed: 0                             master_id
0           74  8423eda8-ae37-11e9-a2fc-000d3a38a36f
1          136  37753730-9b69-11ea-a27a-000d3a38a36f
2         1078  df760a84-ab25-11e9-a2fc-000d3a38a36f
3         1134  fdd08240-244a-11ea-a30f-000d3a38a36f
4         1323  1df22bd2-8549-11ea-80af-000d3a38a36f
5         1484  aa100b7a-d667-11e9-93bc-000d3a38a36f
6         1574  f2affcfc-f186-11e9-9346-000d3a38a36f
7         1682  667a10cc-4fa2-11ea-99ba-000d3a38a36f
8         2002  f1e095a6-637e-11ea-a6dc-000d3a38a36f
9         2060  3a2a6c48-526c-11ea-956d-000d3a38a36f
10        2246  169d1518-9d6e-11e9-9897-000d3a38a36f
11        2401  1e4fcad2-a57d-11e9-a2fc-000d3a38a36f
12        2542  70d34b80-a7e4-11e9-a2fc-000d3a38a36f
13        2763  215e3162-565a-11ea-b9b9-000d3a38a36f
14        3157  25a05fe6-5a84-11eb-9e65-000d3a38a36f
15        3274  c2984396-d622-11e9-93bc-000d3a38a36f
16        3662  63caf5e4-e3be-11e9-ad00-000d3a38a36f
17        3879  b43a543e-5b96-11ea-a3e9-000d3a38a36f
18        3932  f8033de8-b16e-11e9-89fa-000d3a38a36f
19        3996  715f95a2-9f94-11e9-a2fc-000d3a38a36f

**Case 2:
A discount of approximately 40% is planned for men’s and children’s products. The goal is to specifically target past high-value customers who have not shopped for a long time, dormant customers, and new customers who should not be lost but are interested in these categories. Save the IDs of the suitable target customers in a CSV file named discount_target_customer_ids.csv.**

In [15]:
combined[((combined["segment"] == "hibernating") | 
          (combined["segment"] == "cant_loose") | 
          (combined["segment"] == "new_customers")) & 
         ((combined["interested_in_categories_12"].str.contains("ERKEK")) | 
          (combined["interested_in_categories_12"].str.contains("COCUK")))]["master_id"]

7        3f1b4dc8-8a7d-11ea-8ec0-000d3a38a36f
10       ae608ece-c9d8-11ea-a31e-000d3a38a36f
15       13ed97a4-b167-11e9-89fa-000d3a38a36f
19       2730793e-3908-11ea-85d6-000d3a38a36f
21       7b289956-d691-11e9-93bc-000d3a38a36f
29       a46cc34a-a19f-11e9-a2fc-000d3a38a36f
35       7a52fd46-5be8-11ea-a7c9-000d3a38a36f
48       1eb32dea-a409-11e9-a2fc-000d3a38a36f
66       bb548d60-abb6-11e9-a2fc-000d3a38a36f
76       7d58deb6-62fa-11ea-a6dc-000d3a38a36f
91       808005da-a511-11e9-a2fc-000d3a38a36f
108      5bc87a7c-9de8-11e9-9897-000d3a38a36f
122      f318a3de-ad06-11e9-a2fc-000d3a38a36f
130      ae557c64-5b29-11ea-b304-000d3a38a36f
145      5bfa131c-ada5-11e9-a2fc-000d3a38a36f
147      90e0b158-2b54-11ea-9d27-000d3a38a36f
148      ecabc266-a7f6-11e9-a2fc-000d3a38a36f
149      0117c094-63e8-11ea-a6dc-000d3a38a36f
156      c88819fa-d0fb-11ea-8b59-000d3a38a36f
166      9613613c-c9d0-11ea-a31e-000d3a38a36f
170      c25f2eea-265d-11ea-b9a0-000d3a38a36f
175      737ef46a-18eb-11ea-9213-000d3a38a36f
177      06ea4252-5b56-11ea-b15d-000d3a38a36f
187      fac3db2c-9d1f-11e9-9897-000d3a38a36f
203      648eeb1a-983c-11ea-9d91-000d3a38a36f
214      f068ab7c-3990-11ea-85d6-000d3a38a36f
220      7c6ee6da-e531-11ea-b769-000d3a38a36f
222      44cb68d2-5eec-11ea-be5b-000d3a38a36f
227      0f890e44-7f31-11ea-80af-000d3a38a36f
235      175699e0-2ac0-11ea-b3a7-000d3a38a36f
236      6b2d1e68-2d95-11ea-8e71-000d3a38a36f
241      9856d854-b592-11ea-a78c-000d3a38a36f
243      eb1b30a8-a530-11e9-a2fc-000d3a38a36f
246      b1f63c54-d691-11e9-93bc-000d3a38a36f
247      7cefecc8-27b6-11ea-aaaa-000d3a38a36f
262      7aff7b54-abc4-11e9-a2fc-000d3a38a36f
280      9bc68994-5084-11ea-99ba-000d3a38a36f
317      5af055ee-a066-11ea-9d0a-000d3a38a36f
329      9b1ad686-9f5d-11e9-a2fc-000d3a38a36f
331      342bba62-542a-11ea-b1db-000d3a38a36f
335      894ae9ea-bfa6-11ea-9c44-000d3a38a36f
336      4ca21210-a6c1-11e9-a2fc-000d3a38a36f
347      f649fe28-1efc-11ea-81ff-000d3a38a36f
351      8e139dee-673d-11ea-9d38-000d3a38a36f
354      03464e90-8a4d-11ea-8ec0-000d3a38a36f
363      292b3e08-acff-11e9-a2fc-000d3a38a36f
373      a04c6ab8-165c-11ea-aa74-000d3a38a36f
377      1c9f6aa8-ada2-11e9-a2fc-000d3a38a36f
379      648b29d6-d720-11e9-93bc-000d3a38a36f
385      3089494e-eac4-11e9-88c1-000d3a38a36f
388      9a72df9a-9d5e-11e9-9897-000d3a38a36f
400      328d030a-acff-11e9-a2fc-000d3a38a36f
401      6ebf7bc2-a77e-11e9-a2fc-000d3a38a36f
407      1fd54d7a-aae4-11e9-a2fc-000d3a38a36f
413      17663f56-ad63-11e9-a2fc-000d3a38a36f
415      05ff5f30-a256-11e9-a2fc-000d3a38a36f
417      ad874998-9f3b-11e9-9897-000d3a38a36f
419      47df565c-a8f6-11e9-a2fc-000d3a38a36f
423      c331b30a-fc00-11ea-a045-000d3a38a36f
427      d8fef74a-a564-11e9-a2fc-000d3a38a36f
439      5c14aae6-74f7-11ea-bb48-000d3a38a36f
440      72a6cda6-e12d-11e9-957d-000d3a38a36f
452      f349eb80-f340-11e9-9346-000d3a38a36f
465      c1f0a998-15e6-11ea-aa74-000d3a38a36f
492      6ba0e20a-1bfa-11ea-ac4f-000d3a38a36f
499      8586047e-abb2-11e9-a2fc-000d3a38a36f
513      91ee7e70-ad34-11e9-a2fc-000d3a38a36f
514      e5ff2976-1e07-11ea-8bf2-000d3a38a36f
516      2e1f8532-b10e-11e9-9757-000d3a38a36f
537      f36da15a-183a-11ea-9213-000d3a38a36f
541      6aa88bda-aa2d-11e9-a2fc-000d3a38a36f
543      018bc0ba-6ce5-11ea-b576-000d3a38a36f
549      8c891286-af66-11e9-a2fc-000d3a38a36f
553      a007deb8-d0ef-11ea-8b59-000d3a38a36f
556      89784bc0-a570-11e9-a2fc-000d3a38a36f
566      18d7e0a2-5bf4-11ea-be01-000d3a38a36f
577      0d5f9110-2982-11ea-b87a-000d3a38a36f
582      3f927872-a7d3-11e9-a2fc-000d3a38a36f
587      88cfc83c-d19e-11ea-b0fc-000d3a38a36f
590      68ac3810-f67a-11e9-841e-000d3a38a36f
594      4660bd3c-ee0d-11e9-9346-000d3a38a36f
599      c6d7f798-af04-11e9-a2fc-000d3a38a36f
610      090d6e42-9da6-11e9-9897-000d3a38a36f
630      619ce5cc-f36b-11e9-9346-000d3a38a36f
633      07b1fe32-adfa-11e9-a2fc-000d3a38a36f
653      e30c10ec-ab95-11e9-a2fc-000d3a38a36f
657      3586c570-b090-11e9-9757-000d3a38a36f
663      9c49d80e-aabb-11e9-a2fc-000d3a38a36f
667      3ad9aafc-46f8-11ea-b6c0-000d3a38a36f
694      8864f4d0-d636-11e9-93bc-000d3a38a36f
698      ebabaa2e-ae55-11e9-a2fc-000d3a38a36f
706      5adaaf60-6127-11ea-8dd8-000d3a38a36f
709      4d8f288c-8d40-11ea-8f41-000d3a38a36f
711      b93e02d4-9f29-11e9-9897-000d3a38a36f
730      207fd1d2-1268-11ea-a001-000d3a38a36f
754      980c5b34-ab85-11e9-a2fc-000d3a38a36f
759      bb414b60-a887-11e9-a2fc-000d3a38a36f
769      2e112ef0-2b9e-11ea-853d-000d3a38a36f
789      08db7ac2-5bd8-11ea-96de-000d3a38a36f
794      7b96ae8a-f1c3-11e9-9346-000d3a38a36f
798      2acf0f44-53dc-11ea-94d4-000d3a38a36f
805      2000589a-ddd3-11e9-a848-000d3a38a36f
810      2c666002-a255-11e9-a2fc-000d3a38a36f
825      fbfec31a-a73a-11e9-a2fc-000d3a38a36f
829      6ada87a4-7ef1-11ea-80af-000d3a38a36f
841      880a4c80-9786-11ea-a9c8-000d3a38a36f
851      96b2a160-23e1-11ea-8523-000d3a38a36f
857      af6c208e-9fc3-11e9-a2fc-000d3a38a36f
858      cb57eb46-1acc-11ea-98d5-000d3a38a36f
860      20c64e8e-a69b-11e9-a2fc-000d3a38a36f
864      2c9d2c3c-62a7-11ea-9861-000d3a38a36f
868      8267786e-d6bd-11e9-93bc-000d3a38a36f
873      4c5243b8-b06a-11e9-9757-000d3a38a36f
878      30b0df84-9f1c-11e9-9897-000d3a38a36f
880      0b0c120e-889a-11ea-9c02-000d3a38a36f
883      4865ec8c-4377-11ea-8b43-000d3a38a36f
884      b4862718-a73e-11e9-a2fc-000d3a38a36f
885      f3eb9b22-2006-11ea-87bf-000d3a38a36f
912      42f41680-5339-11ea-acd3-000d3a38a36f
924      df7a82da-4b7a-11ea-a626-000d3a38a36f
925      0f4c8b74-5b12-11ea-b524-000d3a38a36f
937      ded9c78e-6b80-11ea-9c62-000d3a38a36f
952      b64eeb04-abd3-11e9-a2fc-000d3a38a36f
960      6201d566-a949-11e9-a2fc-000d3a38a36f
964      9b352790-9ee1-11eb-9c47-000d3a38a36f
967      5ceec9e8-94a9-11ea-85df-000d3a38a36f
969      47e63dbc-27c9-11ea-aaaa-000d3a38a36f
981      2f29799e-1371-11eb-8ffc-000d3a38a36f
989      31aaf3d2-afe9-11ea-b736-000d3a38a36f
992      f7b8490c-a113-11e9-a2fc-000d3a38a36f
993      02d44576-a596-11e9-a2fc-000d3a38a36f
1007     7888020a-deba-11e9-957d-000d3a38a36f
1027     ef669622-5690-11ea-b9b9-000d3a38a36f
1043     44cc6636-a797-11e9-a2fc-000d3a38a36f
1044     daa560bc-aeff-11e9-a2fc-000d3a38a36f
1047     b953bab6-ff27-11ea-9792-000d3a38a36f
1062     928bc03e-5f8d-11ea-be5b-000d3a38a36f
1063     624a30c8-5b36-11ea-913d-000d3a38a36f
1066     b3079abe-a727-11e9-a2fc-000d3a38a36f
1089     3ed92220-aecf-11e9-a2fc-000d3a38a36f
1099     a0312f9e-249b-11ea-bf27-000d3a38a36f
1106     27f11544-1ca3-11ea-a490-000d3a38a36f
1109     2049c722-a567-11e9-a2fc-000d3a38a36f
1110     1d9d5d9c-a588-11e9-a2fc-000d3a38a36f
1113     2a193b24-abdf-11e9-a2fc-000d3a38a36f
1117     22fc5f52-aae9-11e9-a2fc-000d3a38a36f
1118     c3e97256-9d32-11ea-a27a-000d3a38a36f
1119     258d2540-6d0c-11ea-84a8-000d3a38a36f
1123     415c5d12-97d8-11ea-9d91-000d3a38a36f
1138     7d04e8ee-accd-11e9-a2fc-000d3a38a36f
1139     4df312ee-9a55-11ea-9fd8-000d3a38a36f
1147     1927c0e2-9f82-11e9-a2fc-000d3a38a36f
1152     7c1f1696-aebe-11e9-a2fc-000d3a38a36f
1159     a306c258-a50a-11e9-a2fc-000d3a38a36f
1164     be960fca-aeaa-11e9-a2fc-000d3a38a36f
1171     d773b23a-26e7-11ea-aaaa-000d3a38a36f
1175     52c42222-502c-11ea-99ba-000d3a38a36f
1183     996cba92-2f6d-11eb-9c24-000d3a38a36f
1185     8d9bfc3e-2b43-11ea-9d27-000d3a38a36f
1186     74df201c-a831-11e9-a2fc-000d3a38a36f
1190     66f99eac-a3c0-11e9-a2fc-000d3a38a36f
1192     a67c432c-fe42-11e9-a5e8-000d3a38a36f
1193     5b3ba208-f128-11e9-9346-000d3a38a36f
1195     6d04e8ae-215d-11ea-9618-000d3a38a36f
1202     cce83316-245f-11ea-a30f-000d3a38a36f
1209     5d4c7b0c-2be9-11ea-91ab-000d3a38a36f
1214     8e50cca6-1aed-11ea-98d5-000d3a38a36f
1239     58973fe0-a94c-11e9-a2fc-000d3a38a36f
1245     bc2f61c0-afde-11e9-9757-000d3a38a36f
1248     f2b09554-5bda-11ea-ba40-000d3a38a36f
1249     5c0ff6cc-127d-11ea-a001-000d3a38a36f
1258     47b18f9e-ac46-11e9-a2fc-000d3a38a36f
1266     ebbd8dfa-9e3a-11e9-9897-000d3a38a36f
1268     a4bfb076-b001-11e9-9757-000d3a38a36f
1278     87cceb54-66f5-11ea-9d38-000d3a38a36f
1282     45b47a70-b1ab-11e9-89fa-000d3a38a36f
1292     3aa26938-b19e-11e9-89fa-000d3a38a36f
1299     473a1d4a-ffcc-11e9-a5e8-000d3a38a36f
1320     c7ba1696-b16b-11e9-89fa-000d3a38a36f
1328     2ba952c8-d685-11e9-93bc-000d3a38a36f
1330     85e6a5b6-a574-11e9-a2fc-000d3a38a36f
1342     985f83ea-a24d-11e9-a2fc-000d3a38a36f
1344     1797e7dc-84a3-11ea-80af-000d3a38a36f
1349     a93c9b08-ac2f-11e9-a2fc-000d3a38a36f
1353     0a4e6440-a9dc-11e9-a2fc-000d3a38a36f
1369     d39cc798-9e87-11e9-9897-000d3a38a36f
1374     79105a84-acb9-11e9-a2fc-000d3a38a36f
1376     0406e708-2b71-11ea-9d27-000d3a38a36f
1378     fb39e1ce-adef-11e9-a2fc-000d3a38a36f
1404     c28a5b5e-ade2-11e9-a2fc-000d3a38a36f
1408     049db85e-ad18-11e9-a2fc-000d3a38a36f
1412     43edaeb2-1daf-11ea-8bf2-000d3a38a36f
1414     1f84b88e-1ae0-11eb-8d74-000d3a38a36f
1417     fa58e084-ab74-11e9-a2fc-000d3a38a36f
1418     3de952fa-a2d5-11e9-a2fc-000d3a38a36f
1433     aaf10f18-6b80-11ea-9c62-000d3a38a36f
1443     7a79efa6-5ba1-11ea-952c-000d3a38a36f
1450     0fbe9d4a-9555-11ea-85df-000d3a38a36f
1462     9cbc03dc-a725-11e9-a2fc-000d3a38a36f
1467     d4e10526-a1e6-11e9-a2fc-000d3a38a36f
1485     44133df2-a7ea-11e9-a2fc-000d3a38a36f
1487     a2fc586a-5327-11ea-acd3-000d3a38a36f
1495     3b5b6e68-9764-11ea-a9c8-000d3a38a36f
1499     4a2798d0-b124-11e9-9757-000d3a38a36f
1501     fdb961f4-b16e-11e9-89fa-000d3a38a36f
1524     98d54746-ae3d-11e9-a2fc-000d3a38a36f
1532     b1362b0e-2640-11ea-8e1c-000d3a38a36f
1537     7f6d3de0-84ac-11ea-80af-000d3a38a36f
1539     ba161b06-b463-11ea-96bf-000d3a38a36f
1551     b7ad5d1c-5b48-11ea-8dc1-000d3a38a36f
1552     963f0b3c-71d0-11ea-adca-000d3a38a36f
1567     147d3094-191d-11ea-b6a2-000d3a38a36f
1581     77fa07fa-b018-11e9-9757-000d3a38a36f
1593     d377e406-09dd-11eb-8ffc-000d3a38a36f
1597     539a730c-a746-11e9-a2fc-000d3a38a36f
1602     7427c896-a2e5-11e9-a2fc-000d3a38a36f
1613     855e7464-acf1-11e9-a2fc-000d3a38a36f
1638     55ad1332-a7c5-11e9-a2fc-000d3a38a36f
1645     6770946c-8f0a-11eb-8cb8-000d3a38a36f
1655     bc2bd732-b47c-11ea-96bf-000d3a38a36f
1660     7ea7a1b6-29e9-11ea-87cc-000d3a38a36f
1665     97883386-2637-11ea-8e1c-000d3a38a36f
1671     9957d1de-0121-11ea-a5e8-000d3a38a36f
1688     7a5fecb6-b0a0-11e9-9757-000d3a38a36f
1691     1f6ae350-a46c-11e9-a2fc-000d3a38a36f
1698     1cced08c-25a1-11ea-b1c8-000d3a38a36f
1704     847dcabc-f667-11e9-841e-000d3a38a36f
1717     3891eb46-b12b-11e9-9757-000d3a38a36f
1721     b4f414c6-a527-11e9-a2fc-000d3a38a36f
1724     01d5156e-51f9-11ea-a243-000d3a38a36f
1727     91cdfbe6-a52d-11e9-a2fc-000d3a38a36f
1734     3b87b5d4-e046-11e9-957d-000d3a38a36f
1741     541875dc-d693-11e9-93bc-000d3a38a36f
1746     55a1ef62-976a-11ea-a9c8-000d3a38a36f
1750     086664a4-541b-11ea-b1db-000d3a38a36f
1752     9903b490-a4ed-11e9-a2fc-000d3a38a36f
1766     5fe1e444-a8e8-11e9-a2fc-000d3a38a36f
1770     ba9247f2-f35d-11e9-9346-000d3a38a36f
1787     24e7d676-a804-11e9-a2fc-000d3a38a36f
1790     9f767036-a7b0-11e9-a2fc-000d3a38a36f
1793     c40ba2ec-9da4-11e9-9897-000d3a38a36f
1795     4c3b7e74-9f28-11e9-9897-000d3a38a36f
1804     360d188c-432a-11ea-8b43-000d3a38a36f
1809     ac9b64bc-e048-11e9-957d-000d3a38a36f
1814     e7bc5c52-a59e-11e9-a2fc-000d3a38a36f
1832     9fe956d2-abf2-11e9-a2fc-000d3a38a36f
1844     89ede12c-a331-11ea-9c18-000d3a38a36f
1848     b88e7e7c-d033-11ea-9c49-000d3a38a36f
1851     ae853f4e-5bd8-11ea-aef1-000d3a38a36f
1864     15aafbda-9dcc-11e9-9897-000d3a38a36f
1865     18d2b56e-af83-11e9-a2fc-000d3a38a36f
1873     79d37e3a-532e-11ea-acd3-000d3a38a36f
1911     738a9978-a7c1-11e9-a2fc-000d3a38a36f
1912     a091517a-9ea0-11e9-9897-000d3a38a36f
1917     1517dc4e-9f73-11e9-a2fc-000d3a38a36f
1946     02bc6872-bebb-11ea-958c-000d3a38a36f
1947     2fb5042c-acf8-11e9-a2fc-000d3a38a36f
1952     b606fe1c-97e0-11ea-9d91-000d3a38a36f
1969     c4ac012c-630d-11ea-a6dc-000d3a38a36f
1977     6a7ac120-544e-11ea-b1db-000d3a38a36f
1981     134e2b12-5fcf-11ea-8dd8-000d3a38a36f
1983     641b6834-a46d-11e9-a2fc-000d3a38a36f
1996     04d3fc0a-ff2c-11e9-a5e8-000d3a38a36f
2022     497f782c-a151-11e9-a2fc-000d3a38a36f
2026     6bbad8c4-1d4c-11ea-a490-000d3a38a36f
2027     294d2bd8-5bf2-11ea-8c6c-000d3a38a36f
2029     a1ea7ce8-1639-11ea-aa74-000d3a38a36f
2030     5258542e-a9cf-11e9-a2fc-000d3a38a36f
2034     12b48848-0149-11ea-a5e8-000d3a38a36f
2043     217e6ca2-9ecc-11e9-9897-000d3a38a36f
2064     7d0c7fd8-ae0c-11e9-a2fc-000d3a38a36f
2072     74691d2e-24f8-11ea-bf27-000d3a38a36f
2083     74437dbe-aff3-11e9-9757-000d3a38a36f
2084     a8ad11de-a9ca-11e9-a2fc-000d3a38a36f
2085     173f30ac-bde1-11ea-aa61-000d3a38a36f
2089     b6765d24-afa2-11e9-9c23-000d3a38a36f
2103     87dbaee0-a78e-11e9-a2fc-000d3a38a36f
2104     5df4b840-a727-11e9-a2fc-000d3a38a36f
2111     456ac9fa-567f-11eb-9e65-000d3a38a36f
2121     d9bad7e2-20f9-11ea-b50a-000d3a38a36f
2129     0e155206-ac60-11e9-a2fc-000d3a38a36f
2135     34ebde18-a779-11e9-a2fc-000d3a38a36f
2139     72df9d80-f82e-11e9-b138-000d3a38a36f
2153     49942220-190c-11eb-8d74-000d3a38a36f
2172     57fc41c2-a1f2-11e9-a2fc-000d3a38a36f
2183     9de213e6-ad92-11e9-a2fc-000d3a38a36f
2194     fc01cc08-f74a-11e9-841e-000d3a38a36f
2202     74ddd00c-a8b5-11e9-a2fc-000d3a38a36f
2212     806da518-a1cc-11e9-a2fc-000d3a38a36f
2223     a0f0eb4a-1f73-11ea-87bf-000d3a38a36f
2225     043f4824-a5d3-11e9-a2fc-000d3a38a36f
2230     d581ff1e-8635-11eb-a98a-000d3a38a36f
2234     4f859bd2-9db1-11e9-9897-000d3a38a36f
2237     80168054-ddd5-11e9-a848-000d3a38a36f
2238     61828e8e-5bb7-11ea-85d6-000d3a38a36f
2239     1b583826-b038-11e9-9757-000d3a38a36f
2256     3ffd5daa-5be1-11ea-a294-000d3a38a36f
2258     7a2af788-2330-11ea-8523-000d3a38a36f
2265     9082f6d8-9ab4-11ea-9fd8-000d3a38a36f
2266     59ea5c52-a824-11e9-a2fc-000d3a38a36f
2268     99dc7024-abd1-11e9-a2fc-000d3a38a36f
2275     e41ad460-a5e0-11e9-a2fc-000d3a38a36f
2282     1b574e56-b1bf-11e9-89fa-000d3a38a36f
2291     26ac1432-1dd3-11ea-8bf2-000d3a38a36f
2298     c64641ce-a566-11e9-a2fc-000d3a38a36f
2300     66e52d04-5bc2-11ea-ab39-000d3a38a36f
2301     a47a85fe-aafd-11e9-a2fc-000d3a38a36f
2311     ff839e5e-1fdd-11ea-87bf-000d3a38a36f
2314     638d9cce-afef-11e9-9757-000d3a38a36f
2315     c72fcc38-2e6b-11eb-8062-000d3a299ebf
2319     3fccb99e-5b4f-11ea-8848-000d3a38a36f
2325     f582dcc2-abab-11e9-a2fc-000d3a38a36f
2349     5a7afbd4-ab00-11e9-a2fc-000d3a38a36f
2350     a9ee7526-a937-11e9-a2fc-000d3a38a36f
2354     b3ac73c6-39e5-11ea-85d6-000d3a38a36f
2364     ccf13fd6-9e51-11e9-9897-000d3a38a36f
2365     8e5ca6f2-a423-11e9-a2fc-000d3a38a36f
2369     54a22db6-fff2-11ea-8341-000d3a38a36f
2378     e4c8cfd0-f3be-11e9-9346-000d3a38a36f
2385     21c4722a-a0f1-11e9-a2fc-000d3a38a36f
2389     67b251d6-1a58-11ea-941b-000d3a38a36f
2396     cbee6360-f12c-11e9-9346-000d3a38a36f
2417     ba28d314-ae0f-11e9-a2fc-000d3a38a36f
2423     7e67f4ac-62d4-11ea-9861-000d3a38a36f
2442     802715e4-214c-11ea-9618-000d3a38a36f
2447     8601417c-b033-11e9-9757-000d3a38a36f
2451     1ed7d4cc-ad39-11e9-a2fc-000d3a38a36f
2469     01d4c0ba-b3bf-11e9-a043-000d3a38a36f
2484     2f904ee4-d6d2-11e9-93bc-000d3a38a36f
2497     eac83cb0-aa06-11e9-a2fc-000d3a38a36f
2500     4b041628-a956-11e9-a2fc-000d3a38a36f
2505     3110eb3e-2321-11ea-8523-000d3a38a36f
2510     c448b17c-b51a-11e9-9c4b-000d3a38a36f
2519     b860dbd6-a387-11e9-a2fc-000d3a38a36f
2540     1ac6cf4c-ab35-11e9-a2fc-000d3a38a36f
2559     9ea846b6-f10b-11ea-bde9-000d3a38a36f
2569     1e4e189c-5b42-11ea-8231-000d3a38a36f
2576     5a6d9306-27b8-11ea-aaaa-000d3a38a36f
2592     2e4bdc22-8b38-11ea-8ec0-000d3a38a36f
2603     c86258e2-ad65-11e9-a2fc-000d3a38a36f
2604     9e5c2eca-1853-11ea-9213-000d3a38a36f
2608     80ed220e-af0d-11e9-a2fc-000d3a38a36f
2610     0358f300-6eb0-11ea-96d9-000d3a38a36f
2612     1ad652c6-9e85-11e9-9897-000d3a38a36f
2619     fdbe8304-a7ab-11e9-a2fc-000d3a38a36f
2622     13b63ae0-981e-11ea-9d91-000d3a38a36f
2634     dc4d48a6-aec5-11e9-a2fc-000d3a38a36f
2637     42007092-5bd7-11ea-ad33-000d3a38a36f
2643     b6f64a98-a935-11e9-a2fc-000d3a38a36f
2646     234c3ee4-b12b-11e9-9757-000d3a38a36f
2650     6601dfa2-da2d-11e9-93bc-000d3a38a36f
2652     f43156b8-afb2-11e9-9757-000d3a38a36f
2656     836ebcf0-1d3e-11ea-a490-000d3a38a36f
2667     aa46e43c-a79c-11e9-a2fc-000d3a38a36f
2681     7e7e040a-15e4-11ea-aa74-000d3a38a36f
2685     1dbd288e-26d3-11eb-8a9b-000d3a38a36f
2689     67a1c476-2b6d-11ea-9d27-000d3a38a36f
2716     a0ba96c4-48e7-11ea-b6c0-000d3a38a36f
2751     51914cf4-aacd-11e9-a2fc-000d3a38a36f
2752     e6cf4c78-9b6b-11ea-a27a-000d3a38a36f
2780     42552f66-fe1b-11e9-a5e8-000d3a38a36f
2783     9f78b8c2-d72c-11e9-93bc-000d3a38a36f
2798     608fe71c-b01b-11e9-9757-000d3a38a36f
2803     17eec894-a458-11e9-a2fc-000d3a38a36f
2819     2b9fb996-bbbf-11ea-9a91-000d3a38a36f
2839     7b472b6c-aee8-11e9-a2fc-000d3a38a36f
2848     bf86cc76-ac07-11e9-a2fc-000d3a38a36f
2857     3a154aa4-e442-11e9-ad00-000d3a38a36f
2861     42b70084-2b9c-11ea-853d-000d3a38a36f
2863     0b810b9a-b113-11e9-9757-000d3a38a36f
2877     64354114-b3da-11ea-8745-000d3a38a36f
2884     83000634-790a-11ea-b363-000d3a38a36f
2906     fe98b79e-acac-11e9-a2fc-000d3a38a36f
2910     e97ceab8-a2d1-11e9-a2fc-000d3a38a36f
2917     39aa923e-aa3c-11ea-b736-000d3a38a36f
2919     4753016a-389d-11eb-a48e-000d3a38a36f
2921     aa14ba78-b149-11e9-9757-000d3a38a36f
2928     555de2aa-0bfe-11eb-8ffc-000d3a38a36f
2930     6f0199dc-27d3-11ea-aaaa-000d3a38a36f
2932     a89276e6-aa95-11e9-a2fc-000d3a38a36f
2946     a4b6cfea-1f83-11eb-b272-000d3a38a36f
2948     62c4cae4-ffd4-11e9-a5e8-000d3a38a36f
2950     350facba-ac26-11e9-a2fc-000d3a38a36f
2951     671cbaee-a4fa-11eb-aa3b-000d3a299ebf
2956     6e7f071c-5b2a-11ea-bf91-000d3a38a36f
2960     a86293d8-a520-11e9-a2fc-000d3a38a36f
2981     3ad92b8e-5b3b-11ea-8e25-000d3a38a36f
2984     8f0d2298-a413-11ea-bd63-000d3a38a36f
2997     61f98482-fe63-11e9-a5e8-000d3a38a36f
3015     23b1412e-f4a4-11e9-9346-000d3a38a36f
3020     12dd5428-a5b7-11e9-a2fc-000d3a38a36f
3026     bf7db658-5418-11eb-9e65-000d3a38a36f
3028     9e444422-ad32-11e9-a2fc-000d3a38a36f
3044     53206d4c-190f-11ea-9213-000d3a38a36f
3052     b06dd3a4-4d71-11ea-9c12-000d3a38a36f
3055     bf714d6a-c795-11ea-b753-000d3a38a36f
3067     01fa53ea-fbd9-11e9-b138-000d3a38a36f
3074     2681d470-2b7e-11ea-9d27-000d3a38a36f
3077     8b0d0c36-d6f4-11e9-93bc-000d3a38a36f
3078     e4c4d308-4959-11ea-8a4f-000d3a38a36f
3092     5f6632fa-98c9-11ea-b97a-000d3a38a36f
3096     4bb3a040-acc9-11e9-a2fc-000d3a38a36f
3102     1f6e2060-bc44-11ea-aa61-000d3a38a36f
3106     96b8c1a4-5423-11ea-b1db-000d3a38a36f
3109     2902ff9c-ff2a-11e9-a5e8-000d3a38a36f
3125     a85ad1de-a6b9-11ea-bd63-000d3a38a36f
3126     043f4822-b1ce-11e9-89fa-000d3a38a36f
3133     6a11d1fa-a68e-11ea-bd63-000d3a38a36f
3149     882e584a-9da5-11e9-9897-000d3a38a36f
3152     00842ccc-15ea-11ea-aa74-000d3a38a36f
3163     9c9cb028-dd4c-11ea-9c1f-000d3a38a36f
3173     b45921a0-5b39-11ea-ad7e-000d3a38a36f
3178     d1ffc3ae-b00c-11e9-9757-000d3a38a36f
3190     4c5efe6c-228b-11ea-8523-000d3a38a36f
3200     0431764a-a3ed-11ea-9c18-000d3a38a36f
3206     956155ee-514b-11ea-99ba-000d3a38a36f
3219     bf5e8806-532d-11ea-acd3-000d3a38a36f
3232     d8a76050-a269-11e9-a2fc-000d3a38a36f
3250     c9b10362-b0bf-11e9-9757-000d3a38a36f
3253     607d9f00-b177-11e9-89fa-000d3a38a36f
3273     1afb8c0e-23ea-11ea-8523-000d3a38a36f
3280     818d60b4-f88e-11e9-b138-000d3a38a36f
3288     f7dd9642-244b-11ea-a30f-000d3a38a36f
3289     9480650e-a23a-11e9-a2fc-000d3a38a36f
3291     1a70bade-b13a-11e9-9757-000d3a38a36f
3303     c7b7a34a-4d5e-11ea-9c12-000d3a38a36f
3306     02f2627a-ac05-11e9-a2fc-000d3a38a36f
3311     47276484-263c-11ea-8e1c-000d3a38a36f
3316     e6375f16-9d39-11e9-9897-000d3a38a36f
3341     5d8d9912-d675-11e9-93bc-000d3a38a36f
3345     73b4c58c-3dac-11ea-9e19-000d3a38a36f
3348     8f5fd62a-9e3b-11e9-9897-000d3a38a36f
3351     af54f4ca-ad99-11e9-a2fc-000d3a38a36f
3368     831bbdac-e1de-11e9-957d-000d3a38a36f

In [16]:
combined[((combined["segment"] == "hibernating") | 
          (combined["segment"] == "cant_loose") | 
          (combined["segment"] == "new_customers")) & 
         ((combined["interested_in_categories_12"].str.contains("ERKEK")) | 
          (combined["interested_in_categories_12"].str.contains("COCUK")))]["master_id"].to_csv("discount_target_customer_ids.csv")
print(pd.read_csv("discount_target_customer_ids.csv").head(20))

    Unnamed: 0                             master_id
0            7  3f1b4dc8-8a7d-11ea-8ec0-000d3a38a36f
1           10  ae608ece-c9d8-11ea-a31e-000d3a38a36f
2           15  13ed97a4-b167-11e9-89fa-000d3a38a36f
3           19  2730793e-3908-11ea-85d6-000d3a38a36f
4           21  7b289956-d691-11e9-93bc-000d3a38a36f
5           29  a46cc34a-a19f-11e9-a2fc-000d3a38a36f
6           35  7a52fd46-5be8-11ea-a7c9-000d3a38a36f
7           48  1eb32dea-a409-11e9-a2fc-000d3a38a36f
8           66  bb548d60-abb6-11e9-a2fc-000d3a38a36f
9           76  7d58deb6-62fa-11ea-a6dc-000d3a38a36f
10          91  808005da-a511-11e9-a2fc-000d3a38a36f
11         108  5bc87a7c-9de8-11e9-9897-000d3a38a36f
12         122  f318a3de-ad06-11e9-a2fc-000d3a38a36f
13         130  ae557c64-5b29-11ea-b304-000d3a38a36f
14         145  5bfa131c-ada5-11e9-a2fc-000d3a38a36f
15         147  90e0b158-2b54-11ea-9d27-000d3a38a36f
16         148  ecabc266-a7f6-11e9-a2fc-000d3a38a36f
17         149  0117c094-63e8-11ea-a6dc-000d3a38a36f
18         156  c88819fa-d0fb-11ea-8b59-000d3a38a36f
19         166  9613613c-c9d0-11ea-a31e-000d3a38a36f

***“Thank you for reviewing!” 😊***


***EBUBEKİR TİLBAÇ***


![](https://www.icegif.com/wp-content/uploads/2024/12/thank-you-icegif-7.gif)